spring:
  application:
    name: restone
eureka:
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 10